import React, { useState, useEffect } from 'react';
import { houseAPI, areaAPI } from '../api';
import { FaHome, FaTimes } from 'react-icons/fa';

const HouseModal = ({ isOpen, onClose, onSubmit, initialData, loadDataForTab }) => {
  const [formData, setFormData] = useState({
    house_name: '',
    family_name: '',
    location_name: '',
    area: '',
    address: ''
  });
  const [areas, setAreas] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(null);

  useEffect(() => {
    if (isOpen) {
      // Load areas when modal opens
      loadAreas();

      if (initialData) {
        setFormData({
          house_name: initialData.house_name || '',
          family_name: initialData.family_name || '',
          location_name: initialData.location_name || '',
          area: initialData.area?.id || initialData.area || '',
          address: initialData.address || ''
        });
      } else {
        setFormData({
          house_name: '',
          family_name: '',
          location_name: '',
          area: '',
          address: ''
        });
      }
      // Reset status messages when modal opens
      setError(null);
      setSuccess(null);
    }
  }, [initialData, isOpen]);

  const loadAreas = async () => {
    try {
      const response = await areaAPI.getAll();
      setAreas(response.data);
    } catch (err) {
      console.error('Failed to load areas:', err);
    }
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setSuccess(null);

    try {
      // Prepare data for submission
      const submitData = { ...formData };

      if (initialData) {
        // Update existing house
        await houseAPI.update(initialData.home_id, submitData);
        setSuccess('House updated successfully!');
      } else {
        // Create new house (home_id will be auto-generated by backend)
        await houseAPI.create(submitData);
        setSuccess('House created successfully!');
      }

      // Reload house data
      if (loadDataForTab) {
        loadDataForTab('houses', true); // Force reload
      }

      // Close modal after a short delay
      setTimeout(() => {
        onClose();
        onSubmit && onSubmit(submitData);
      }, 1500);
    } catch (err) {
      setError(err.response?.data?.detail || err.response?.data?.message || err.response?.data || 'Failed to save house');
      console.error('Error saving house:', err);
    } finally {
      setLoading(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="modal-overlay">
      <div className="modal-content animate-in">
        <div className="modal-header">
          <h2>
            <div className="header-icon-wrapper">
              <FaHome />
            </div>
            {initialData ? 'Edit House' : 'Add New House'}
          </h2>
          <button className="close-btn" onClick={onClose}><FaTimes /></button>
        </div>
        <form onSubmit={handleSubmit} className="modal-body">
          <div className="input-wrapper">
            <label htmlFor="house_name">House Name *</label>
            <input
              type="text"
              id="house_name"
              name="house_name"
              value={formData.house_name}
              onChange={handleChange}
              required
              disabled={loading}
              placeholder="Enter house name"
            />
          </div>

          <div className="input-wrapper">
            <label htmlFor="family_name">Family Name *</label>
            <input
              type="text"
              id="family_name"
              name="family_name"
              value={formData.family_name}
              onChange={handleChange}
              required
              disabled={loading}
              placeholder="Enter family name"
            />
          </div>

          <div className="input-wrapper">
            <label htmlFor="location_name">Location Name *</label>
            <input
              type="text"
              id="location_name"
              name="location_name"
              value={formData.location_name}
              onChange={handleChange}
              required
              disabled={loading}
              placeholder="Enter location name"
            />
          </div>

          <div className="input-wrapper">
            <label htmlFor="area">Area *</label>
            <select
              id="area"
              name="area"
              value={formData.area}
              onChange={handleChange}
              required
              disabled={loading}
            >
              <option value="">Select an area</option>
              {areas.map(area => (
                <option key={area.id} value={area.id}>
                  {area.name}
                </option>
              ))}
            </select>
          </div>

          <div className="input-wrapper">
            <label htmlFor="address">Address</label>
            <textarea
              id="address"
              name="address"
              value={formData.address}
              onChange={handleChange}
              rows="3"
              disabled={loading}
              placeholder="Enter full address"
            />
          </div>

          {(error || success) && (
            <div className={`status-banner ${error ? 'error' : 'success'}`}>
              {error || success}
            </div>
          )}

          <div className="form-actions" style={{ marginTop: '24px' }}>
            <button
              type="button"
              className="btn-secondary"
              onClick={onClose}
              disabled={loading}
            >
              Cancel
            </button>
            <button
              type="submit"
              className="btn-primary"
              disabled={loading}
            >
              {loading ? (
                <>
                  <span className="spinner"></span>
                  {initialData ? 'Updating...' : 'Creating...'}
                </>
              ) : (
                initialData ? 'Update House' : 'Create House'
              )}
            </button>
          </div>

        </form>
      </div>
    </div>
  );
};

export default HouseModal;