# Generated by Django 5.2.5 on 2025-10-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='isGuardian',
            field=models.BooleanField(default=False),
        ),
    ]
