# Generated by Django 5.2.5 on 2025-10-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0002_member_isguardian'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='surname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
