# Generated by Django 5.2.5 on 2025-10-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0003_member_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='firebase_config',
            field=models.TextField(blank=True, help_text='Firebase configuration JSON', null=True),
        ),
    ]
