# Generated by Django 5.2.5 on 2026-01-07 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0004_appsettings_firebase_config'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcollection',
            unique_together={('collection', 'year', 'name')},
        ),
    ]
