# Generated by Django 5.2.5 on 2026-01-07 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0005_alter_subcollection_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='general_body_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='married_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse', to='society.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='married_to_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='married_to_surname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
