# Generated by Django 5.2.5 on 2026-01-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0009_alter_member_adhar'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='firebase_enabled',
            field=models.BooleanField(default=True, help_text='Global switch to enable/disable Firebase sync'),
        ),
    ]
